CREATE TABLE HOTELS
(
    NUMHO INTEGER NOT NULL,
    NOMHO VARCHAR(20) NOT NULL,
    RUEADRHO VARCHAR(20) NOT NULL,
    VILLEHO VARCHAR(20) NOT NULL,
    NBETOILESHO INTEGER NOT NULL,
    
    CONSTRAINT HOTELS_PK PRIMARY KEY
    (
        NUMHO
    )

);

CREATE TABLE TYPESCHAMBRE
(
    NUMTY INTEGER NOT NULL,
    NOMTY VARCHAR(20) NOT NULL,
    PRIXTY INTEGER NOT NULL,
    
    CONSTRAINT TYPESCHAMBRE_PK PRIMARY KEY
    (
        NUMTY
    )
);

CREATE TABLE CHAMBRES 
(
  NUMCH INTEGER NOT NULL,
  NUMHO INTEGER NOT NULL REFERENCES HOTELS,
  
  CONSTRAINT CHAMBRES_PK PRIMARY KEY 
  (
    NUMCH, NUMHO 
  ),
  NUMTY INTEGER NOT NULL REFERENCES TYPESCHAMBRE
  
);


CREATE TABLE CLIENTS
(
    NUMCL INTEGER NOT NULL,
    NOMCL VARCHAR(20) NOT NULL,
    PRENOMCL VARCHAR(20) NOT NULL,
    RUEADRCL VARCHAR(20) NOT NULL,
    VILLECL VARCHAR(20) NOT NULL,
    
    CONSTRAINT CLIENTS_PK PRIMARY KEY
    (
        NUMCL
    )

);

CREATE TABLE RESERVATIONS 
(
    NUMCL INTEGER NOT NULL REFERENCES CLIENTS,
    NUMHO INTEGER NOT NULL REFERENCES HOTELS,
    NUMTY INTEGER NOT NULL REFERENCES TYPESCHAMBRE,
    DATEA TIMESTAMP NOT NULL,
    
    CONSTRAINT RESERVATION_PK PRIMARY KEY
    (
        NUMCL, NUMHO, NUMTY, DATEA
    ),
    NBJOURS INTERVAL DAY(3) TO SECOND(0) NOT NULL,
    NBCHAMBRES INTEGER NOT NULL
);


CREATE TABLE OCCUPATIONS 
(
    NUMCL INTEGER NOT NULL REFERENCES CLIENTS,
    NUMHO INTEGER NOT NULL REFERENCES HOTELS,
    NUMCH INTEGER NOT NULL, FOREIGN KEY (NUMCH, NUMHO) REFERENCES CHAMBRES (NUMCH, NUMHO),
    DATEA TIMESTAMP NOT NULL,
    DATED TIMESTAMP NOT NULL,
    
    CONSTRAINT OCCUPATIONS_PK PRIMARY KEY
    (
        NUMHO, NUMCH, DATEA
    )
);


CREATE VIEW HOTEL_1
    AS
    SELECT NUMCL ,
    NUMTY ,
    DATEA ,
    NBJOURS ,
    NBCHAMBRES  FROM RESERVATIONS WHERE NUMHO ='1';
    

INSERT INTO HOTEL_1 (NUMCL, NUMTY, DATEA, NBJOURS, NBCHAMBRES)
VALUES
('1', '1', CURRENT_TIMESTAMP, INTERVAL '3' DAY ,'1');







